### ISSUE TITLE
getMaterialProgram optimisations

### ISSUE THREAD

**Issue by dmnsgn** [pex-gl/pex-renderer#102]
Possible item to benchmark:

- `flags += 'f'` vs `flags.push('f')`
- Program cache hash: caching is using the vert/frag source as object key which makes the key very long (for PBR shader for instance): 
https://github.com/pex-gl/pex-renderer/blob/master/index.js#L259-L260
Possible solutions: https://www.npmjs.com/package/rev-hash, https://www.npmjs.com/package/string-hash
- `if` vs `&&`
- cache flags

**Comment by vorg** [comment]
This has been dramatically improved in e2819742e2a557cf3b5e0595c55f655791077af4 where i switched from string concat to comparing vert, frag and flags separately. For the Materials example `getMaterialProgram` dropped from 10% CPU usage to 0.5%.

I'm closing this now as further optimisations should happen in pex-context (building comands) and material in general (not having that many pipelines so less flags to build and compare in the first place).
