### ISSUE TITLE
Dithering observed on texture resize

### ISSUE THREAD

**Issue by dmnsgn** [pex-gl/pex-renderer#103]
Dithering is observed, when resizing the context with post processing off.

![screen shot 2018-10-24 at 14 28 14](https://user-images.githubusercontent.com/1636460/47511538-55134e00-d872-11e8-9d9b-f79aa73a2710.png)

Use case is a custom shader and problem is emphasised when tonemapping/encoding is omitted.

**Comment by vorg** [comment]
It's most likely same bug as [Toggling post-processing leaves a ghost buffer on screen (AO?)](https://github.com/pex-gl/pex-renderer/issues/106)

Do we have a test case? Otherwise i'll close this one.

**Comment by dmnsgn** [comment]
Hasn't been observed since fixing post processing component. Closing.
