### ISSUE TITLE
Toggling post-processing leaves a ghost buffer on screen (AO?)

### ISSUE THREAD

**Issue by dmnsgn** [pex-gl/pex-renderer#106]
![screenshot 2018-10-30 at 16 27 41](https://user-images.githubusercontent.com/1636460/47733865-178f3600-dc61-11e8-887f-ae94c5c694ba.png)

Bottom of the plane with the image of the scene before I disabled postpro

**Comment by vorg** [comment]
Fixed in bca0fcce902417a42685deb928e3248c17b03b0e
