### ISSUE TITLE
Point light influence gets cropped 

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#109]
Expanding range seems to hit an arbitrary limit and results in hard edge 

<img width="580" alt="screenshot 2018-11-06 at 08 48 52" src="https://user-images.githubusercontent.com/171001/48082234-f347d200-e1e9-11e8-9543-86003c5098fc.png">

**Comment by vorg** [comment]
Verify with https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_lights_punctual/README.md

**Comment by dmnsgn** [comment]
Actually happening still: I am assuming because far is hardcoded to 10.0 here: https://github.com/pex-gl/pex-shaders/blob/0c4cabb8f23a54b8655fb0f15a432bc01782f1b0/shaders/chunks/shadowing.glsl.js#L177
