### ISSUE TITLE
Enhanced texCoord support

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#116]
### 1. Tex coords scale and offset

Useful for texturing floors (scale) or using sprite sheets (scale + offset)

```glsl
uniform float uTexCoord0Scale;
uniform vec2 uTexCoord0Offset;
```

### 2.Multiple tex coords support

Useful for lightmaps. It would also require a way to assigning given texture to given texture coords attribute.

```glsl
attribute vec2 texCoord0;
attribute vec2 texCoord1;
```

- [x] Q: How is glTF dealing with it?

**Comment by dmnsgn** [comment]
There are no references to scale and offset properties in the glTF specs. So that would be only convenience.

**Comment by vorg** [comment]
Here 
> [KHR_texture_transform
](https://github.com/KhronosGroup/glTF/blob/master/extensions/2.0/Khronos/KHR_texture_transform/README.md) To support this use case, this extension adds offset, rotation, and scale

**Comment by vorg** [comment]
Also glTF supports at least TEXCOORD_0 and TEXCOORD_1

https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#meshes

**Comment by dmnsgn** [comment]
Ha so there is texture transform as an extension, fair enough.
As for the multiple textCoord, what's the use case apart from using it for lightmap or aomap?

**Comment by vorg** [comment]
I’m not aware of other common usecases for secondary UVs beside baked lights/ao.

**Comment by dmnsgn** [comment]
> 2.Multiple tex coords support

PR here: https://github.com/pex-gl/pex-renderer/pull/177/files

**Comment by vorg** [comment]
Wow. That's a big PR. Where does `. texCoord` idea comes from? Is that how three is doing it?

**Comment by vorg** [comment]
Implementation in the PR requires modifying texture objects from pex context

```javascript
var tex = ctx.texture2D()
material.baseColorMap = tex
material.baseColorMap.texCoord = 1
```

Proposal: In various places of pex context we support "data or opts" approach. Similar solution could be used here
```javascript
material.baseColorMap = { texture: tex, texCoord: 1 }
```

This will also come handy if we implement [KHR_texture_transform](https://github.com/KhronosGroup/glTF/blob/65fabf38a23527ebedefa301487088346eee2a9b/extensions/2.0/Khronos/KHR_texture_transform/README.md)

```javascript
material.baseColorMap = {
  texture: tex,
  texCoord: 1,
  offset: [0, 1],
  scale: [1, -1]
}
```

**Comment by dmnsgn** [comment]
Three doesn't have support for it. They have aomap always using uv2 and if this second set of uv is not supplied by the glTF model, they duplicate the buffer attributes for uv1; basically sending the same coordinates twice (if I got this right).

Babylon.js has support for it and they do it in a similar fashion by setting a `coordinatesIndex` property eg. my texCoord; and then sending an uniform with info: `this._activeEffect.setFloat2("vDiffuseInfos", this.diffuseTexture.coordinatesIndex, this.diffuseTexture.level);`

**Comment by vorg** [comment]
My worry is that we will need to send all those coordinates all the time just to handle 5% cases where we actually have 2 coords.

**Comment by dmnsgn** [comment]
Good point about not modifying the original texture. That will require an extra check in when drawing:
```js
if (material.baseColorMap) cachedUniforms.uBaseColorMap = material.baseColorMap
// becomes
if (material.baseColorMap) {
  cachedUniforms.uBaseColorMap = material.baseColorMap.texture || material.baseColorMap
}
```
Is that acceptable?

**Comment by vorg** [comment]
Yes, that's what i mean.

As for `uBaseColorMapTexCoordIndex` maybe we make it `#define` ? it's not like they change from fame to frame..

**Comment by dmnsgn** [comment]
I can try with a define indeed.

**Comment by vorg** [comment]
I've reopened the issue as documentation is missing in [material](https://github.com/pex-gl/pex-renderer#material--renderermaterialopts) section.
