### ISSUE TITLE
Use getShaderPrecisionFormat to check if highp precision is available in shader

### ISSUE THREAD

**Issue by dmnsgn** [pex-gl/pex-renderer#122]
API could default to `highp` and be overrided manually, but check `getShaderPrecisionFormat` in every case:
```js
renderer = createRenderer(opts)
const renderer = createRendererer({
  ...,
 precision: 'highp' // 'lowp' || 'mediump'
})
```

**Comment by vorg** [comment]
I think in the context of pex-renderer it’s safe to assume such device would not be able to run it anyway.

**Comment by vorg** [comment]
@dmnsgn I'm re-opening this issue due to https://github.com/variablestudio/var-18007-mccann-cathay-pacific-artmap/issues/75

**Comment by dmnsgn** [comment]
PR in progress: https://github.com/pex-gl/pex-renderer/pull/125

**Comment by vorg** [comment]
In that context this comment from [Filament docs](https://google.github.io/filament/Filament.md.html) makes more sense

> This solution solves the storage problem but requires intermediate computations to be performed with single precision floats. We would instead prefer to perform all (or at least most) of the lighting work using half precision floats instead. Doing so can greatly improve performance and power usage, particularly on mobile devices. Half precision floats are however ill-suited for this kind of work as common illuminance and luminance values (for the sun for instance) can exceed their range. The solution is to simply pre-expose the lights themselves instead of the result of the lighting pass. This can be done efficiently on the CPU if updating a light's constant buffer is cheap. This can also be done on the GPU, as shown in listing 25.

**Comment by vorg** [comment]
ThreeJS work "towards mediump"

- [Textures Rendered as Black on (some?) devices with Android 7+](https://github.com/mrdoob/three.js/issues/14137#issuecomment-397856954) lot's of horror stories as it seem that they are not mediump ready
- [Materials: Consider to use mediump for all shaders](https://github.com/mrdoob/three.js/issues/14570) more up to date discussion

**Comment by dmnsgn** [comment]
It probably won't fixes all bugs magically but at least provide support for other precisions which could be a good start before planning anything else.

**Comment by vorg** [comment]
I'm not sure about this approach

```javascript
const renderer = createRendererer({
  ...,
 precision: 'highp' // 'lowp' || 'mediump'
})
```

After reading all the references above it seems that correct way is to have everything as low as possible because without bugs a) save energy on mobile, b) on desktop it doesn't matter (i.e. it's always "highest quality"). Maybe i need to learn more about ThreeJS approach but the "everything is mediump" way implemented in https://github.com/pex-gl/pex-renderer/pull/125 might be hard to manage as individual uniforms might need to be tweaked (e.g. positions hi/med, colors low etc).

**Comment by vorg** [comment]
BabylonJS does [string replacement](https://github.com/BabylonJS/Babylon.js/blob/f3b4098c0f3f00f7f3993494bf833af266160b1b/src/Materials/effect.ts#L741) on all shaders if `highp` is not supported. Hmm. So is anybody doing per variable precision optimisations beside some autogenerated/cross-compiled shaders in AAA engines like unity?

**Comment by dmnsgn** [comment]
I have never seen any WebGL shader in the wild making use of per variable precision setting (eg. no `uniform highp mat4 uModelMatrix;`)

**Comment by vorg** [comment]
If we are not interested in per-variable precision tweaking why not automate the whole thing in `pex-context` and get rid of `getMaxPrecision` in favour of `capabilities.fragmentPrecisionHigh` boolean for simpler shaders switches or troubleshooting (https://github.com/pex-gl/pex-context/pull/60#issuecomment-455558438)

**Comment by dmnsgn** [comment]
Would it still be possible to have per material precision with this approach?

**Comment by vorg** [comment]
> I have never seen any WebGL shader in the wild making use of per variable precision setting (eg. no

@dmnsgn 

```glsl
#version 300 es
precision mediump float;
precision mediump int;
layout(std140) uniform FrameUniforms
{
highp mat4 viewFromWorldMatrix;
highp mat4 worldFromViewMatrix;
highp mat4 clipFromViewMatrix;
highp mat4 viewFromClipMatrix;
highp mat4 clipFromWorldMatrix;
highp mat4 worldFromClipMatrix;
highp mat4 lightFromWorldMatrix;
highp vec4 resolution;
highp vec3 cameraPosition;
highp float time;
```

or

```glsl
precision mediump float;
precision mediump int;
layout(std140) uniform PostProcessUniforms
{
vec2 uvScale;
float time;
float yOffset;
} postProcessUniforms;
uniform mediump sampler2D postProcess_colorBuffer;
in highp vec2 vertex_uv;
````

**Comment by vorg** [comment]
I think we should test it our pex-renderer materials with mediump devices and use GL_FRAGMENT_PRECISION_HIGH for portability.

**Comment by vorg** [comment]
Not sure how much is that relevant in 2023
