### ISSUE TITLE
Normal mapping doesn't work on iPhoneX

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#123]
It works fine on iPhone 7. Switching back to `highp` in the fragment shader fixes the issue.

Mozilla actually recommends avoiding mediump if possible https://developer.mozilla.org/en-US/docs/Web/API/WebGL_API/WebGL_best_practices

**Comment by dmnsgn** [comment]
Shader uses highp:

https://github.com/pex-gl/pex-renderer/blob/90a39cb5b751e67eb8390aacff0ccb2bbcaa81c8/systems/renderer/pex-shaders/shaders/chunks/normal-perturb.glsl.js#L5-L9

https://github.com/pex-gl/pex-shaders/blob/cb6db08184414ed8a17ff22864d53b424528e35a/shaders/chunks/normal-perturb.glsl.js#L6-L9
