### ISSUE TITLE
Add orthographic camera

### ISSUE THREAD

**Issue by simonharrisco** [pex-gl/pex-renderer#127]
Do we need it? Pros/Cons?

Pros: 
- You can actually measure data on a screen and get an accurate representation of values
- Grid systems are prettier

Cons:
- Limited usefulness

Either way, here is an orthographic camera component. 

```js
const Signal = require('signals')
const vec3 = require('pex-math/vec3')
const mat4 = require('pex-math/mat4')
const utils = require('pex-math/utils')

function OrthoCamera (opts) {
    const gl = opts.ctx.gl
    this.type = 'Camera'
    this.changed = new Signal()
  
    // camera
    this.left = -1
    this.right = 1
    this.bottom = -1
    this.top = 1
    this.near = 0.1
    this.far = 100
    this.scale = 1
    this.backgroundColor = [0, 0, 0, 1]
    this.projectionMatrix = mat4.ortho(mat4.create(), this.left, this.right, this.bottom, this.top, this.near, this.far)
  
    this.viewMatrix = mat4.create()
    this.inverseViewMatrix = mat4.create()
    this.postprocess = false;

    this.viewport = [0, 0, gl.drawingBufferWidth, gl.drawingBufferHeight]
    this._textures = []
    this.exposure = 1
}

OrthoCamera.prototype.init = function (entity) {
    this.entity = entity
}

OrthoCamera.prototype.set = function (opts) {
    Object.assign(this, opts)
    this.dirty = true

    if ( opts.scale) {
        this.left = -1 * opts.scale
        this.right = 1 * opts.scale
        this.bottom = -1 * opts.scale
        this.top = 1 * opts.scale
        mat4.ortho(this.projectionMatrix, this.left, this.right, this.bottom, this.top, this.near, this.far)
    }

    
    if (opts.viewport) {
        const viewport = opts.viewport
        const aspect = viewport[2] / viewport[3]
        if (this.aspect !== aspect) {
            this.set({ aspect: aspect })
        }
        this._textures.forEach((tex) => {
            const expectedWidth = Math.floor(viewport[2] * (tex.sizeScale || 1))
            const expectedHeight = Math.floor(viewport[3] * (tex.sizeScale || 1))
            if (tex.width !== expectedWidth || tex.height !== expectedHeight) {
            // console.log('update texture size', tex.width, expectedWidth, tex.height, expectedHeight)
            this.ctx.update(tex, {
                width: expectedWidth,
                height: expectedHeight
            })
            }
        })
    }
    
    Object.keys(opts).forEach((prop) => this.changed.dispatch(prop))  
}

OrthoCamera.prototype.update = function () {
    mat4.set(this.inverseViewMatrix, this.entity.transform.modelMatrix)
    mat4.set(this.viewMatrix, this.entity.transform.modelMatrix)
    mat4.invert(this.viewMatrix)
  }

module.exports = function createOrthoCamera (opts) {
    return new OrthoCamera(opts)
  }
```

**Comment by dmnsgn** [comment]
glTF does include both perspective and orthographic types so this should probably make it to the core at some point: https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#cameras

**Comment by simonharrisco** [comment]
```{"nodes":[{"id":"aDq7rY6f2","name":"OrthoCamera","x":-8565,"y":-4680,"templateName":"Custom","code":"var vec3 = require('pex-math').vec3\nvar mat4 = require('pex-math').mat4\nvar quat = require('pex-math').quat\nvar euler = require('pex-math').euler\nconst Signal = require('signals')\nconst utils = require('pex-math').utils\nvar toDegrees = require('pex-math').utils.toDegrees\nvar toRadians = require('pex-math').utils.toRadians\n\nvar viewport = node.in('viewport', [0, 0, 1, 1], { connectable: false })\nvar tags = node.in('tags', '', { connectable: false })\n\nvar ctx = graph.ctx\nvar renderer = graph.renderer\n\nvar renderIn = node.triggerIn('in')\nvar renderOut = node.triggerOut('out')\n\n\nconst position = node.in('position', [0, 5, 5])\nconst rotation = node.in('rotation', [0, 0, 0])\n\nconst scale = node.in('scale', 15)\nconst near = node.in('near', 1)\nconst far = node.in('far', 300)\n\n\nfunction OrthoCamera (opts) {\n    const gl = opts.ctx.gl\n    this.type = 'Camera'\n    this.changed = new Signal()\n  \n    // camera\n    this.left = -1\n    this.right = 1\n    this.bottom = -1\n    this.top = 1\n    this.near = 0.1\n    this.far = 100\n    this.scale = 1\n    this.backgroundColor = [0, 0, 0, 1]\n    this.projectionMatrix = mat4.ortho(mat4.create(), this.left, this.right, this.bottom, this.top, this.near, this.far)\n  \n    this.viewMatrix = mat4.create()\n    this.inverseViewMatrix = mat4.create()\n    this.postprocess = false;\n\n    this.viewport = [0, 0, gl.drawingBufferWidth, gl.drawingBufferHeight]\n    this._textures = []\n    this.exposure = 1\n}\n\nOrthoCamera.prototype.init = function (entity) {\n    this.entity = entity\n}\n\nOrthoCamera.prototype.set = function (opts) {\n    Object.assign(this, opts)\n    this.dirty = true\n\n    if ( opts.scale) {\n        this.left = -1 * opts.scale\n        this.right = 1 * opts.scale\n        this.bottom = -1 * opts.scale\n        this.top = 1 * opts.scale\n        mat4.ortho(this.projectionMatrix, this.left, this.right, this.bottom, this.top, this.near, this.far)\n    }\n\n    \n    if (opts.viewport) {\n        const viewport = opts.viewport\n        const aspect = viewport[2] / viewport[3]\n        if (this.aspect !== aspect) {\n            this.set({ aspect: aspect })\n        }\n        this._textures.forEach((tex) => {\n            const expectedWidth = Math.floor(viewport[2] * (tex.sizeScale || 1))\n            const expectedHeight = Math.floor(viewport[3] * (tex.sizeScale || 1))\n            if (tex.width !== expectedWidth || tex.height !== expectedHeight) {\n            // console.log('update texture size', tex.width, expectedWidth, tex.height, expectedHeight)\n            this.ctx.update(tex, {\n                width: expectedWidth,\n                height: expectedHeight\n            })\n            }\n        })\n    }\n    \n    Object.keys(opts).forEach((prop) => this.changed.dispatch(prop))  \n}\n\nOrthoCamera.prototype.update = function () {\n    mat4.set(this.inverseViewMatrix, this.entity.transform.modelMatrix)\n    mat4.set(this.viewMatrix, this.entity.transform.modelMatrix)\n    mat4.invert(this.viewMatrix)\n  }\n\nfunction createOrthoCamera (opts) {\n  return new OrthoCamera(opts)\n}\n\n\n\nconst transformCmp = renderer.transform({\n  position: position.value\n})\n\nposition.onChange = () => {\n  console.log('camera position set ' + position.value)\n  transformCmp.set({ position: position.value })\n}\n                   \nrotation.onChange = () => {\n  console.log('camera rotation set ' + rotation.value)  \n  quat.fromEuler(\n    transformCmp.rotation,\n    rotation.value.map(toRadians)\n  )\n  transformCmp.set({ rotation: transformCmp.rotation })\n}\n\nvar cameraCmp = renderer.orthocamera(ctx)\n\nvar cameraEnt = renderer.entity([\n  cameraCmp,\n  transformCmp\n], tags.value.split(' '))\n\ntags.onChange = function () {\n  cameraEnt.tags = tags.value ? tags.value.split(' ') : []\n}\n\nfunction onChange () {\n  cameraCmp.set({\n    //backgroundColor: backgroundColor.value,\n    scale: scale.value,\n    near: near.value,\n    far: far.value\n  })\n}\n\n\nscale.onChange = onChange\nnear.onChange = onChange\nfar.onChange = onChange\n\nvar rot = [0, 0, 0]\nvar rotDeg = [0, 0, 0]\nrenderIn.onTrigger = function (props) {\n  if (!vec3.equals(position.value, transformCmp.position)) {\n    vec3.set(position.value, transformCmp.position)\n  }\n  euler.fromQuat(rot, transformCmp.rotation)\n  rotDeg[0] = toDegrees(rot[0])\n  rotDeg[1] = toDegrees(rot[1])\n  rotDeg[2] = toDegrees(rot[2])\n  if (!vec3.equals(rotation.value, rotDeg)) {\n    vec3.set(rotation.value, rotDeg)\n  }  \n  \n  if (ctx && (ctx.gl.drawingBufferWidth.width !== cameraCmp.viewport[2] || ctx.gl.drawingBufferHeight !== cameraCmp.viewport[3])) {\n    var v = viewport.value\n    var view = [\n      ctx.gl.drawingBufferWidth * v[0],\n      ctx.gl.drawingBufferHeight * v[1],\n      ctx.gl.drawingBufferWidth * v[2],\n      ctx.gl.drawingBufferHeight * v[3]\n    ]\n    \n    cameraCmp.set({\n      viewport: view\n    })\n  }\n\n  var entity = [cameraEnt]\n  props.parentEntity.push(entity)\n  var newProps = Object.assign({}, props, {\n    parentEntity: entity\n  })\n  renderOut.trigger(newProps)\n}\n\nconsole.log('camera position ' + position.value)\n","params":[{"name":"viewport","public":false,"value":[0,0,1,1],"script":""},{"name":"tags","public":false,"value":"","script":""},{"name":"in","public":false,"source":{"id":"-Mr54SDtwG","port":"out1"}},{"name":"position","public":false,"value":[-4.61,31.87,4.05],"script":""},{"name":"rotation","public":false,"value":[-81.96,-7.780000000000087,-44.04999999999999],"script":""},{"name":"scale","public":false,"value":21.14,"script":""},{"name":"near","public":false,"value":4,"script":""},{"name":"far","public":false,"value":50,"script":""}]}],"comments":[]}```

This is a working orthocam node that you can just drop into a project if you want to, its a bit messy but its works.

**Comment by simonharrisco** [comment]
Above doesnt account for aspect ratio.

**Comment by vorg** [comment]
Another difference is they use the following properties to describe the orthographic projection.

```javascript
camera.orthographic.xmag;
camera.orthographic.ymag;
camera.orthographic.zfar;
camera.orthographic.znear;
```

I would assume that our `left`, `right` are `-xmag`, `xmag` and the same for `top`, `bottom` match `ymag`, `-ymag`. 

Probably worth comparing with [pex-math/mat4.ortho](https://github.com/pex-gl/pex-math/blob/master/mat4.js#L450) matrix.

> Above doesnt account for aspect ratio.

Doesn't it? In which way? Do you mean `right-left / top-bottom` should match `window.innerWidth / window.innerHeight`?

**Comment by simonharrisco** [comment]
<img width="1940" alt="screenshot 2019-01-16 at 09 45 30" src="https://user-images.githubusercontent.com/36566034/51240391-808a6e00-1973-11e9-8673-87c77568a7aa.png">
<img width="422" alt="screenshot 2019-01-16 at 09 45 19" src="https://user-images.githubusercontent.com/36566034/51240392-808a6e00-1973-11e9-854f-a002ab95ef74.png">

Viewport is assumed square, so yes, I think` right-left / top-bottom` should match `window.innerWidth / window.innerHeight`

`I would assume that our left, right are -xmag, xmag and the same for top, bottom match ymag, -ymag`. Yes I think so, I used the naming from pex-math mat4.ortho for internal consistency

**Comment by vorg** [comment]
I think it would be easier to test this if we switch to a branch and PR. For example `this._textures.forEach((tex) => {` this should crash as we don't have postprocessing in this ortho camera? (how to separate postprocessing from camera is a topic on it's own btw).

**Comment by dmnsgn** [comment]
PR started for splitting camera and post-processing: https://github.com/pex-gl/pex-renderer/issues/127
We could have a new property type (as per glTF) for perspective/orthographic and decide what to do with post-processing there.

**Comment by vorg** [comment]
@dmnsgn btw I like your `issueNumber-name` branch names!

**Comment by dmnsgn** [comment]
Coming from Atlassia JIRA/BitBucket 🤫It is fully automated there though.
