### ISSUE TITLE
Vertex color alpha is not used

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#129]
I would assume that `vertexColor` alpha contributes to opacity but that's not the case and only `rgb` values are used.

https://github.com/pex-gl/pex-renderer/blob/master/shaders/pipeline/material.frag.js#L111

We assign opacity from base color here https://github.com/pex-gl/pex-renderer/blob/master/shaders/chunks/base-color.glsl.js#L14

**Comment by dmnsgn** [comment]
Fixed by https://github.com/pex-gl/pex-renderer/pull/133
