### ISSUE TITLE
Split camera and post-processing in 2 components

### ISSUE THREAD

**Issue by dmnsgn** [pex-gl/pex-renderer#131]

**Comment by vorg** [comment]
What's your plan here? What will happen if I add `Postprocessing` component to and entity without `Camera` ?

**Comment by dmnsgn** [comment]
Nothing should happen. `PostProcessing` will be dependant on a `Camera` component to be present. Same scenario as if an entity had only a `Transform` component.

Underlying necessity of this is too make the Camera component about camera only and prepare the work for having a camera type: https://github.com/pex-gl/pex-renderer/issues/127
