### ISSUE TITLE
Security module updates

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#134]
- [x] Upgrade `cached-path-relative` to version 1.0.2 or later in `examples/postprocessing/package-lock.json`
- [x] Upgrade `cached-path-relative` to version 1.0.2 or later in `examples/lights/package-lock.json`
- [x] Upgrade `merge` to version 1.2.1 or later ` examples/blocks/package-lock.json`

**Comment by dmnsgn** [comment]
Vulnerabilities are coming from the `stanford-dragon` module. PR opened there: https://github.com/hughsk/stanford-dragon

**Comment by vorg** [comment]
The thing about 'stanford-dragon' is that it unpacks itself to 68MB while converting to js on install. I have 6 of those on my hdd and had more.. Let's give him a week and switch to mid-res obj < 10MB instead?

**Comment by dmnsgn** [comment]
Fixed by https://github.com/pex-gl/pex-renderer/commit/41796e4b00fe1f0d4d4800418fa73505ed0c4a98
