### ISSUE TITLE
Setting wireframe rendering on material instead of geometry

### ISSUE THREAD

**Issue by simonharrisco** [pex-gl/pex-renderer#139]
Currently you set the primitive when you define the geometry 
eg:
```
renderer.geometry({
  GeometryComponent,
  primitive: graph.ctx.Primitive.Lines
})
```

Is this the best place to declare this? Would it made more sense to have it set within the material?
Is this a more logical place to put it as materials effect how things look?

Threejs does this
```
material = new THREE.MeshBasicMaterial({
    color: 0xff0000,
    wireframe: true
});
```

BabylonJs does this
```
var myMaterial = new BABYLON.StandardMaterial("myMaterial", scene);
myMaterial.wireframe = true;
```

This reasoning breaks down if the primitive type given in the geometry also supports things like `TRIANGLE_STRIP`,`TRIANGLE FAN` ETC.

What does everyone think?

**Comment by dmnsgn** [comment]
v4: better off using a material type while we see if gl.Lines needs to be abstracted in its own renderer https://github.com/pex-gl/pex-renderer/issues/311#issuecomment-1536368265
