### ISSUE TITLE
glTF flight helmet: no transparency

### ISSUE THREAD

**Issue by dmnsgn** [pex-gl/pex-renderer#140]

**Comment by vorg** [comment]
![screenshot 2019-01-24 at 14 16 05](https://user-images.githubusercontent.com/171001/51683828-a4d4f300-1fe2-11e9-85ba-d9347dfb1440.jpg)

Looks transparent to me? Screenshot from 'examples/gltf.js after switching to online model path (pushed to master)

**Comment by vorg** [comment]
![screenshot 2019-01-24 at 14 16 05](https://user-images.githubusercontent.com/171001/51683933-db127280-1fe2-11e9-83f1-fc039b1711d6.jpg)

Looks ok on my machine?

**Comment by dmnsgn** [comment]
Was mentioned in the Port examples issue. I can't reproduce on my machine either so I'll close.
