### ISSUE TITLE
glTF damaged helmet: no emissive

### ISSUE THREAD

**Issue by dmnsgn** [pex-gl/pex-renderer#141]
Is it normal as https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0#pbr-models doesn't have emissive map checked?

**Comment by vorg** [comment]
Nice, we should do PR with pex-renderer once we have built-in support https://github.com/cx20/gltf-test/issues/2

**Comment by dmnsgn** [comment]
Current look:

<img width="856" alt="Screenshot 2019-04-02 at 17 38 03" src="https://user-images.githubusercontent.com/1636460/55420637-65d99580-556f-11e9-9799-0e3442d34017.png">

Emissive pops well with an hdr skybox, not so much with the default sky so I'll close this one.
