### ISSUE TITLE
Add ACES tonemapping

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#155]
Default Uncharted2
![screen shot 2019-03-07 at 18 06 53](https://user-images.githubusercontent.com/171001/53945022-facda800-4103-11e9-9dcb-795539e85ed0.jpg)

ACES
![screen shot 2019-03-07 at 18 07 45](https://user-images.githubusercontent.com/171001/53945028-fef9c580-4103-11e9-94ae-4cfc38067775.jpg)

It's not only much more saturated but also much brighter? (check gamma)

```glsl
vec3 tonemapAces( vec3 x ) {
    float tA = 2.5;
    float tB = 0.03;
    float tC = 2.43;
    float tD = 0.59;
    float tE = 0.14;
    return clamp((x*(tA*x+tB))/(x*(tC*x+tD)+tE),0.0,1.0);
}
```

**Comment by dmnsgn** [comment]
Have you tried this implementation: https://github.com/TheRealMJP/BakingLab/blob/master/BakingLab/ACES.hlsl

**Comment by vorg** [comment]
Even more options here https://github.com/dmnsgn/glsl-tone-map

**Comment by vorg** [comment]
Implemented
