### ISSUE TITLE
Verify glTF 2.0 examples

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#163]
- [x] run examples/gltf.js via `npx budo gltf.js --open --live`
- [x] remove all models from `models` array [gltf.js#L215](https://github.com/pex-gl/pex-renderer/blob/master/examples/gltf.js#L215)
- [x] add label to gui showing clicked model name
- [x] go through all the examples by clicking their thumbnails and verify with [expected images](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TextureTransformTest) they load correctly creating bug for each model that fails

**Comment by vorg** [comment]
Example bug in [Texture Transform Test](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TextureTransformTest)

Expected
![screenshot](https://user-images.githubusercontent.com/171001/54989698-741e3380-4ffc-11e9-8285-4272ef0f8853.jpg)

Current render
![Screenshot 2019-03-26 at 19 21 42](https://user-images.githubusercontent.com/171001/54989708-7aacab00-4ffc-11e9-9c27-a936ce77c2d4.jpg)

Issue
Lack of [KHR_texture_transform](https://github.com/KhronosGroup/glTF/blob/65fabf38a23527ebedefa301487088346eee2a9b/extensions/2.0/Khronos/KHR_texture_transform/README.md)

**Comment by simonharrisco** [comment]
### Tests

2 cylinder engine : working
Alpha blend mode test : Fail, no default cutoff. The glTF specification names 0.5 as the default, so this is a test failure.
Animated cube:  doesn’t animate (no spin)
Animated morph cube: doesn’t animate
Animated morph sphere : doesn’t animate
Animated triangle: doesn’t animate
Antique camera: working
Avacado: working
Barramundi fish: looks lighter than their screenshot ?
Boom box:  working
Boom box with Axes: working
Box : working
Box animated: working
Box with interleaved positions and normal attribute: broken
Box textured : looks fine but hard to know which face it wants forward from the image on the gihub page
Box textured none power of 2 : looks fine but hard to know which face it wants forward from the image on the gihub page
box vertex colours:  working
BrainStem: not animated
Buggy : working
Cameras : ?!maybe works
CesiumMan : no animation
CesiumMilkTruck  : working
Corset : working
Cube : working
DamagedHelmet: working 
Duck : working
EnvironmentTest : working
FlightHelmet : working
GearboxAssy : working but its far from the center
InterpolationTest : nothing shows
Lantern : might work, lantern looks brighter on there screenshot
MetalRoughSpheres : working
Monster: not animated 
MorphPrimitivesTest : nothing shows
MultiUVTest : texture says ‘multiple UV’s are not supported in this viewer’
NormalTangentMirrorTest : working
NormalTangentTest : working
OrientationTest : working
ReciprocatingSaw : working
RiggedFigure : doesn’t animate
RiggedSimple : doesn’t animate 
SciFiHelmet : working
SimpleMeshes :working
SimpleMorph : nothing shows
SimpleSparseAccessor : not rendering spikes properly
SpecGlossVsMetalRough : not functional, bottles should look the same but KHR_materials_pbrSpecularGlossiness isntt matallic
Sponza : working
Suzanne : working
TextureCoordinateTest : working
TextureSettingsTest : double sided is failing
TextureTransformTest  : completely broken as documented, also not removed when changing model
Triangle : working
TriangleWithoutIndices : working
TwoSidedPlane : not 2 sided
UnlitTest : failed . https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/UnlitTest
VC : no animation
VertexColorTest : working
WaterBottle: rendering more reflective but working


So to split by issues and no issues

### Issues

Alpha blend mode test : Fail, no default cutoff. The glTF specification names 0.5 as the default, so this is a test failure.
Animated cube:  doesn’t animate (no spin)
Animated morph cube: doesn’t animate
Animated morph sphere : doesn’t animate
Animated triangle: doesn’t animate
Barramundi fish: looks lighter than their screenshot ?
Box with interleaved positions and normal attribute: broken
Box textured : looks fine but hard to know which face it wants forward from the image on the gihub page
Box textured none power of 2 : looks fine but hard to know which face it wants forward from the image on the gihub page
BrainStem: not animated
Cameras : ?! maybe works, i believe a gltf file adds a camera and this used the pex camera entity added in the code
CesiumMan : no animation
GearboxAssy : working but its far from the center
InterpolationTest : nothing shows
Lantern : might work, lantern looks brighter on there screenshot
Monster: not animated 
MorphPrimitivesTest : nothing shows
MultiUVTest : texture says ‘multiple UV’s are not supported in this viewer’
RiggedFigure : doesn’t animate
RiggedSimple : doesn’t animate 
SimpleMorph : nothing shows
SimpleSparseAccessor : not rendering spikes properly
SpecGlossVsMetalRough : not functional, bottles should look the same but KHR_materials_pbrSpecularGlossiness isntt matallic
TextureSettingsTest : double sided is failing
TextureTransformTest  : completely broken as documented, also not removed when changing model
TwoSidedPlane : not 2 sided
UnlitTest : failed . https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/UnlitTest
VC : no animation
WaterBottle: rendering more reflective but working


### No issues

2 cylinder engine : working
Antique camera: working
Avacado: working
Boom box:  working
Boom box with Axes: working
Box : working
Box animated: working
box vertex colours:  working
Buggy : working
CesiumMilkTruck  : working
Corset : working
Cube : working
DamagedHelmet: working 
Duck : working
EnvironmentTest : working
FlightHelmet : working
GearboxAssy : working but its far from the center
MetalRoughSpheres : working
NormalTangentMirrorTest : working
NormalTangentTest : working
OrientationTest : working
ReciprocatingSaw : working
SciFiHelmet : working
SimpleMeshes :working
Sponza : working
Suzanne : working
TextureCoordinateTest : working
Triangle : working
TriangleWithoutIndices : working
VertexColorTest : working

**Comment by vorg** [comment]
@simonharrisco I would suggest switching to table layout and how only one row per model (e.g. no separate "working" vs "issue" lists. Using very short "ok" will enable quick scan and reveal models with outstanding or fixed issues.

|Model|Status|
|------|-------|
|Working Model| ok|
|Broken Model | nothing shows  possibly #164 |
|Another Now Fixed Model |  ok ~~#164~~ |

**Comment by dmnsgn** [comment]
All models now loading and working (see `examples/gltf.js`, removing Filter models). Any issue should be addressed as an individual issue.

To note:
- Clipped models: 2CylinderEngine, EnvironmentTest
- MultiUVTest: wrong position is messing with the orbiter
