### ISSUE TITLE
[gltf] Interpolation example not interpolating

### ISSUE THREAD

**Issue by simonharrisco** [pex-gl/pex-renderer#168]
Interpolation example from gltf.js file not working
![image](https://user-images.githubusercontent.com/36566034/55069437-fac62580-507b-11e9-8d1a-acca2dfe1655.png)
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/InterpolationTest

**Comment by dmnsgn** [comment]
😂I guess this answer Marcin following comment:
```js
// TODO: does it ever happen?
```

**Comment by dmnsgn** [comment]
The problem comes from an undefined `accessor.componentType`

**Comment by dmnsgn** [comment]
Added support for BYTE, UNSIGNED_BYTE and SHORT. Now animation is missing.

**Comment by dmnsgn** [comment]
https://github.com/KhronosGroup/glTF/blob/master/specification/2.0/README.md#appendix-c-spline-interpolation

**Comment by simonharrisco** [comment]
Still error in cubicspline 
![slomo](https://user-images.githubusercontent.com/36566034/55468713-dfb76080-55fb-11e9-8fc2-b2b9e7f8a2e4.gif)

**Comment by simonharrisco** [comment]
Every engines examples look different....

ThreeJs
https://cx20.github.io/gltf-test/examples/threejs/index.html?category=tutorialModels&model=InterpolationTest&scale=1&type=glTF

BabylonJs
https://cx20.github.io/gltf-test/examples/babylonjs/index.html?category=tutorialModels&model=InterpolationTest&scale=1&type=glTF

And the 'expected' gif is very short
![image](https://user-images.githubusercontent.com/36566034/55475067-d08bdf00-560a-11e9-8c9b-3de4b2918a6f.png)

**Comment by vorg** [comment]
Do quick search on the repo of gltf and gltf sample models for issues with interpolation

**Comment by simonharrisco** [comment]
Nothing mention apart from what is obvious above, linear scale model is not linear but cubic spline

**Comment by dmnsgn** [comment]
To double check when https://github.com/KhronosGroup/glTF-Sample-Models/issues/213 is solved.

**Comment by dmnsgn** [comment]
Fixed here https://github.com/KhronosGroup/glTF-Sample-Models/pull/230
