### ISSUE TITLE
[gltf] Multiple UVs example not working in gltf.js

### ISSUE THREAD

**Issue by simonharrisco** [pex-gl/pex-renderer#169]
![image](https://user-images.githubusercontent.com/36566034/55069689-8b046a80-507c-11e9-82d1-8b32782e7cd8.png)

Should look like this:
![image](https://user-images.githubusercontent.com/36566034/55069718-99eb1d00-507c-11e9-9082-c35a835f2912.png)
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/MultiUVTest

**Comment by dmnsgn** [comment]
https://github.com/pex-gl/pex-renderer/issues/116
