### ISSUE TITLE
[gltf] SpecGlossVsMetalRough test fails in gltf.js example 

### ISSUE THREAD

**Issue by simonharrisco** [pex-gl/pex-renderer#170]
![image](https://user-images.githubusercontent.com/36566034/55070135-8096a080-507d-11e9-8023-9c13e06f9316.png)

expected
![image](https://user-images.githubusercontent.com/36566034/55070145-855b5480-507d-11e9-833f-09cfd52cd124.png)

because  KHR_materials_pbrSpecularGlossiness extension not supported

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SpecGlossVsMetalRough

**Comment by dmnsgn** [comment]
`// TODO: verify we don't need to multiply by 1 - metallic like above`: turns out we needed to.
