### ISSUE TITLE
[gltf] SimpleSparseAccessor failing in gltf.js example

### ISSUE THREAD

**Issue by simonharrisco** [pex-gl/pex-renderer#171]
![image](https://user-images.githubusercontent.com/36566034/55071128-af157b00-507f-11e9-884e-60da5cbc2410.png)

expected:

![image](https://user-images.githubusercontent.com/36566034/55071150-b63c8900-507f-11e9-9e20-6886dec4a9ef.png)
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/SimpleSparseAccessor

**Comment by dmnsgn** [comment]
To be implemented: https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#sparse-accessors
