### ISSUE TITLE
[gltf] Unlit model test not working in gltf.js

### ISSUE THREAD

**Issue by simonharrisco** [pex-gl/pex-renderer#173]
Im not sure if this because its trying to import a scene without lights? or whether its a texture thing but this is what was found:

![image](https://user-images.githubusercontent.com/36566034/55071483-a5404780-5080-11e9-87d6-534bb9ae5593.png)

wheras expected is: 
![image](https://user-images.githubusercontent.com/36566034/55071587-ee909700-5080-11e9-93d9-a66ada1ea04b.png)
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/UnlitTest

**Comment by dmnsgn** [comment]
<img width="764" alt="Screenshot 2019-03-27 at 17 25 08" src="https://user-images.githubusercontent.com/1636460/55098267-611b6a00-50b5-11e9-93c3-25e9501dc8dc.png">

Added KHR_materials_unlit extensions. c66a48cecfff1273dfa46a539fd1d334ab0da38e

Other issue about color not in linear space (`data.baseColor = decode(uBaseColor, 3).rgb;`) is tracked here: https://github.com/pex-gl/pex-renderer/issues/36
