### ISSUE TITLE
[gltf] Lack of KHR_texture_transform causing TextureTransformTest to fail in gltf.js

### ISSUE THREAD

**Issue by simonharrisco** [pex-gl/pex-renderer#176]
![image](https://user-images.githubusercontent.com/36566034/55075648-6bc10980-508b-11e9-9cf7-5f14b1a36f87.png)

Expected:
![image](https://user-images.githubusercontent.com/36566034/55075598-4af8b400-508b-11e9-9f45-c05001d02d66.png)

https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/TextureTransformTest

KHR texture transform docs:
https://github.com/KhronosGroup/glTF/blob/65fabf38a23527ebedefa301487088346eee2a9b/extensions/2.0/Khronos/KHR_texture_transform/README.md

**Comment by dmnsgn** [comment]
https://github.com/pex-gl/pex-renderer/issues/116
