### ISSUE TITLE
[gltf] NormalTangentTest backface is flipped

### ISSUE THREAD

**Issue by dmnsgn** [pex-gl/pex-renderer#182]
https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/NormalTangentTest

Expected:
![](https://raw.githubusercontent.com/KhronosGroup/glTF-Sample-Models/master/2.0/NormalTangentTest/screenshot/back-side.png)

Current (It is expected to see the sky below the ground in the reflections):
<img width="827" alt="Screenshot 2019-04-01 at 12 35 10" src="https://user-images.githubusercontent.com/1636460/55324645-9e4b7780-547a-11e9-96ae-56fd252cea46.png">

**Comment by simonharrisco** [comment]
Well spotted, damn

**Comment by dmnsgn** [comment]
Same issue with the NormalTangentMirrorTest
