### ISSUE TITLE
[glTF] SpecularGlossiness workflow example labels have different appearances

### ISSUE THREAD

**Issue by dmnsgn** [pex-gl/pex-renderer#186]
> The labels floating above the water bottles should also have the same visual appearance (other than the text of the label being different). One should not be shiny or more reflective than the other.

<img width="387" alt="Screenshot 2019-04-03 at 12 14 06" src="https://user-images.githubusercontent.com/1636460/55474839-22803500-560a-11e9-9209-5d7aac05a553.png">

**Comment by vorg** [comment]
Anybody would mind if we drop support for KHR_materials_pbrSpecularGlossiness?

Nodoby is using it.. even Filament... I thought...

> 2019-04-08 Update: due to popular demand we'll probably go ahead and add a new shading model to Filament itself. https://github.com/google/filament/issues/1068

Cesium also added it half a year ago https://cesium.com/blog/2018/10/22/specular-glossiness-materials-support/

:/

**Comment by dmnsgn** [comment]
Yep it is still there and I would keep it as you don't always have complete control on the pipeline when working with 3D assets.

**Comment by vorg** [comment]
Yep.. meh

> We begrudgingly added it because a lot of glTF models seem to be using the spec-gloss extension.  Maybe the sketchfab exporter uses it.

https://twitter.com/prideout/status/1151491799011041280

**Comment by vorg** [comment]
Fixed via https://github.com/pex-gl/pex-renderer/commit/9b3aa2796dff713ef33645953f092e042b5078c2 must be that label metallic is 0 and we were defaulting to 1 as 0 wasn't properly handled.
