### ISSUE TITLE
Confusion between transform.matrix and transform.position/rotation/scale

### ISSUE THREAD

**Issue by dmnsgn** [pex-gl/pex-renderer#195]
Currently a transform component is the combination of position/rotation/scale multiplied by matrix if it exists.

Any reason to store this extra matrix component (or vice-versa position/rotation/scale)? The orbiter doesn't account for it. As a result, it is not possible to have only transform.matrix to define an object transformation (eg. a camera) and update it with an orbiter.

Nowhere in pex-renderer codebase the transform.matrix is used if I am correct.

**Comment by vorg** [comment]
Its required for gltf compatibility. We might try matrix decomposition but i bad some problems with that in the past. 

Are gltf cameras transforms matrices?

**Comment by dmnsgn** [comment]
glTF cameras are nodes like any other, so they can have either translation/rotation/scale or matrix.

I'd be more inclined to have only one set of local transformation information per transform but you're saying the following can cause issues?
```js
const transform = node.matrix
    ? {
      position: [
        node.matrix[12],
        node.matrix[13],
        node.matrix[14]
      ],
      rotation: quat.fromMat4(quat.create(), node.matrix),
      scale: [
        Math.hypot(node.matrix[0], node.matrix[1], node.matrix[2]),
        Math.hypot(node.matrix[4], node.matrix[5], node.matrix[6]),
        Math.hypot(node.matrix[8], node.matrix[9], node.matrix[10])
      ]
    }
    : {
      position: node.translation || [0, 0, 0],
      rotation: node.rotation || [0, 0, 0, 1],
      scale: node.scale || [1, 1, 1]
    }
```

**Comment by vorg** [comment]
Seems like the [glTF2.0 Spec](https://github.com/KhronosGroup/glTF/tree/master/specification/2.0#transformations) mandates that decomposition is always possible. 
> Matrices must be decomposable to TRS. This implies that transformation matrices cannot skew or shear.

@damien For the record: where is your code from?

Todo:
- [ ] implement above change and remove node.matrix
- [ ] check glTF examples

**Comment by dmnsgn** [comment]
Our source: https://github.com/pex-gl/pex-renderer/blob/master/loaders/glTF.js#L529
Reference from: https://github.com/KhronosGroup/glTF-Sample-Viewer/blob/master/src/node.js#L58 

Important fix they did: https://github.com/KhronosGroup/glTF-Sample-Viewer/commit/89045ce125d989f55c21a69a06e987730745b3fa

**Comment by vorg** [comment]
Does it mean it's already implemented?

**Comment by dmnsgn** [comment]
v4: transform system still use transform.matrix.
https://github.com/pex-gl/pex-renderer/blob/90a39cb5b751e67eb8390aacff0ccb2bbcaa81c8/systems/transform.js#L16

While glTF decompose: https://github.com/pex-gl/pex-renderer/blob/90a39cb5b751e67eb8390aacff0ccb2bbcaa81c8/loaders/glTF.js#L807-L831

TODO: do we keep the property or deem it confusing and remove.

**Comment by vorg** [comment]
How does it work with bones animations? Are they decomposed?

**Comment by vorg** [comment]
I suggest removing it from transform system as gltf now decomposes matrices into TRS
