### ISSUE TITLE
Geometry dispose doesn't delete buffers

### ISSUE THREAD

**Issue by dmnsgn** [pex-gl/pex-renderer#202]
See glTF example where changing models keeps increasing the numbers of buffers.

**Comment by dmnsgn** [comment]
Current workaround:
```js
function cleanUpGeometryBuffers(ctx, geometry) {
  if (geometry._indices.buffer) ctx.dispose(geometry._indices.buffer)

  Object.values(geometry._attributes).forEach((attribute) => {
    if (attribute.buffer) ctx.dispose(attribute.buffer)
  });
}
```

**Comment by dmnsgn** [comment]
v4: we have no dispose implemented anywhere

**Comment by vorg** [comment]
New World and RenderEngine classes implements dispose by calling dispose on all the system

**Comment by dmnsgn** [comment]
Added option to pass entities to render engine too in 12adc6c
