### ISSUE TITLE
loadScene default options

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#203]
I'm creating this issue to discuss the defaults.

Should `skipCameras` default to `true` or (be replaced with `includeCameras: false`

Should we add `skipLights` defaulting to `true` or (be replaced with `includeLights: false`

Most common scenario is using glTF as asset format for meshes to be included in already existing "scene". This will be even more relevant once we add support for image based lighting as it would create situations where lights or reflection maps can leak out of the loaded model to the whole scene.

**Comment by dmnsgn** [comment]
Consensus = default to:
- no camera
- no lights

**Comment by dmnsgn** [comment]
Fixed in 238760148862d3c315609ed8dad18ff08deacc8a (side note: lights aren't loaded yet but I added the default options as a reminder)
