### ISSUE TITLE
Missing point light shadow map preview 

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#204]
In light example there is missing point light shadow map preview
<img width="266" alt="Screenshot 2019-05-03 at 13 25 37" src="https://user-images.githubusercontent.com/171001/57137193-01486b00-6da7-11e9-9f91-98a7254aa202.png">

**Comment by dmnsgn** [comment]
<img width="266" alt="57137193-01486b00-6da7-11e9-9f91-98a7254aa202" src="https://user-images.githubusercontent.com/1636460/59357226-5b333d80-8d22-11e9-96e7-1f86608d1cb7.png">

It is there, just far and dark
