### ISSUE TITLE
Enable linear filtering for point light shadow maps

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#206]
https://github.com/pex-gl/pex-renderer/blob/master/point-light.js#L49

![Screenshot 2019-05-03 at 13 39 07](https://user-images.githubusercontent.com/171001/57137825-df4fe800-6da8-11e9-90bb-877e4713baa7.jpg)

**Comment by dmnsgn** [comment]
Investigate if it's just about filtering or PCF is needed

**Comment by vorg** [comment]
Hard edge comes from [getPunctualShadow](https://github.com/pex-gl/pex-renderer/blob/master/shaders/chunks/shadowing.glsl.js#L102) not from texture filtering. So at least we need lerp like [texture2DShadowLerp](https://github.com/pex-gl/pex-renderer/blob/master/shaders/chunks/shadowing.glsl.js#L34) and of course even better [PCF5x5](https://github.com/pex-gl/pex-renderer/blob/master/shaders/chunks/shadowing.glsl.js#L61)

**Comment by vorg** [comment]
Check if changing NEAREST to LINEAR in [shadowMapDesc](https://github.com/pex-gl/pex-renderer/blob/v4/systems/renderer/descriptors.js#L21) makes any difference

**Comment by dmnsgn** [comment]
getPunctualShadow doesn't use SHADOW_QUALITY nor bias or shadow map size.

**Comment by dmnsgn** [comment]
Only PCS 3x but good enough for now with the better map size.
