### ISSUE TITLE
DOF bug

### ISSUE THREAD

**Issue by nicknikolov** [pex-gl/pex-renderer#21]
Macbook Pro (Retina, 13-inch, Mid 2014)
Intel Iris 1536 MB

<img src='https://shipusercontent.com/b269000ede4ee03c8646046960f0c87a/Screen%20Shot%202017-05-23%20at%2010.39.32.jpg' title='Screen Shot 2017-05-23 at 10.39.32.jpg' width=1548>

**Comment by vorg** [comment]
This will be fixed by implementing https://github.com/pex-gl/pex-renderer/issues/35
