### ISSUE TITLE
VC.gltf model orientation is not displayed correctly

### ISSUE THREAD

**Issue by cx20** [pex-gl/pex-renderer#215]
I tried to display [VC.gltf](https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/VC) with pex-renderer.
However, the orientation of the model does not seem to be displayed correctly.

[pex-renderer v3.0.0-34 + VC.gltf result:](https://rawcdn.githack.com/cx20/gltf-test/cc9bac62e28bfe575b185e963e0d3d6e872cc6ec/examples/pex/index.html?category=sampleModels&model=VC&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/59472407-4b7a3d00-8e79-11e9-9a89-fc2afb207689.png)

[three.js r106dev result:](https://rawcdn.githack.com/cx20/gltf-test/cc9bac62e28bfe575b185e963e0d3d6e872cc6ec/examples/threejs/index.html?category=sampleModels&model=VC&scale=0.2&type=glTF)
![image](https://user-images.githubusercontent.com/1833979/59472621-099dc680-8e7a-11e9-9ddc-0738a9d3b001.png)

**Comment by dmnsgn** [comment]
Seems to be related to our matrix decomposition: https://github.com/KhronosGroup/glTF-Sample-Viewer/commit/89045ce125d989f55c21a69a06e987730745b3fa

**Comment by cx20** [comment]
@dmnsgn Thank you for fixing it.
Please tell me how to update [pex-renderer.min.js](https://github.com/cx20/gltf-test/blob/master/libs/pex/3.0.0-34/pex-renderer.min.js) if you can do it.
