### ISSUE TITLE
Clarify documentation regarding tagging entities 

### ISSUE THREAD

**Issue by simonharrisco** [pex-gl/pex-renderer#218]
> Note on tagging: Camera component also accepts tags. Only entities matching one or more camera tags will be rendered. If camera doesn't have any tags only untagged entities will be rendered.

This is misleading and needs rewording

> Only entities matching one or more ___camera’s entity__ tags will be rendered. If camera doesn’t have any tags only untagged entities will be rendered.

Something like the above. Or perhaps tags should have their own section as the docs?

**Comment by vorg** [comment]
Continued in Layer System https://github.com/pex-gl/pex-renderer/issues/329
