### ISSUE TITLE
Add enabled property to each component

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#22]
Currently only transform has it

**Comment by dmnsgn** [comment]
Branch created: https://github.com/pex-gl/pex-renderer/tree/property-enabled
- [X] Transform
- [X] Lights
- [ ] Skybox
- [ ] Reflection probes
- [X] Geometry
- [ ] Material?
- [ ] Camera
- [ ] Orbiter
- [ ] Overlay
- [ ] Animation
- [ ] Skin
- [ ] Morph
