### ISSUE TITLE
Agree on default camera parameters

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#235]
Could we do some research what Babylon, Unity physical camera and Unity postprocessing stack, Three and UE4 are using for aperture, focal length and fstop?

**Comment by simonharrisco** [comment]
https://docs.google.com/spreadsheets/d/1XyVwOd838bmILoQL-Mv0P9f_V9Y-MBIFz9pedUeFPHA/edit#gid=0

started here temporarily

**Comment by vorg** [comment]
It's all arbitrary so decided on
focalLength = 50mm (-> fov 27deg, or 45deg for 9:16)
fStop = 2.8
