### ISSUE TITLE
Geometry.set(falsyValue) throws an error

### ISSUE THREAD

**Issue by dmnsgn** [pex-gl/pex-renderer#245]
Trying to get ctx from null
```js
Geometry.prototype.set = function(opts) {
  const ctx = opts.ctx || this.ctx
```

Solution: default to opts = {}

**Comment by vorg** [comment]
What's the default parameters support in the browsers?

When would you call `geometry.set(null)` ?

**Comment by dmnsgn** [comment]
Pretty good: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters#Browser_compatibility

`geometry.set(null)` unintentionally of course in Nodes. But could be used to clean buffers pr something maybe (thinking out loud)?

**Comment by dmnsgn** [comment]
v4 components don't have .set() anymore.
