### ISSUE TITLE
DirectionalLight tries to dipose undefined pipeline

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#246]
Here [directional-light.js#L104](https://github.com/pex-gl/pex-renderer/blob/master/directional-light.js#L104)
```
ctx.dispose(this._shadowMapDrawCommand.pipeline)
```

**Comment by dmnsgn** [comment]
Related: https://github.com/pex-gl/pex-renderer/issues/223 (Trying to dispose undefined resource)

**Comment by vorg** [comment]
Closed as duplicate of https://github.com/pex-gl/pex-renderer/issues/223
