### ISSUE TITLE
Consider removing Signals

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#248]
Signal.dispatch generates junk every frame by calling `Array.prototype.slice.call(arguments)` which contributes to GC.

Any real use case where they are still needed?

**Comment by dmnsgn** [comment]
I have never used it so I am in favour of removing it.
Nowadays if I needed to listen for property change I would probably use Proxy getter/setter.

**Comment by dmnsgn** [comment]
TODO v4: remove the dependency when cleaning up components
