### ISSUE TITLE
Add spotlight-like shadows to area light

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#26]

**Comment by vorg** [comment]
The cone angle of the shadow should be depended on the are light size. This has to be a heuristic.

**Comment by vorg** [comment]
Precise and expensive shadows for area lights https://eheitzresearch.wordpress.com/705-2/

**Comment by dmnsgn** [comment]
Added spotlight like shadow (not very flexible with angle default to Math.PI / 2 but can achieve good result with soft shadows 
based on width/height * radius). Create a new issue for more complex shadow implementation.

**Comment by vorg** [comment]
There is some clipping plane issue where for most default scenarios the shadows don't show up.

![Image](https://github.com/user-attachments/assets/d5624da2-30aa-42b8-8318-4b355b68a439)

I have to be very far or directly on top
![Image](https://github.com/user-attachments/assets/ce630908-5770-441e-a960-fad438358291)

![Image](https://github.com/user-attachments/assets/bef50a4a-6f51-4af1-a2f4-d17949527a7d)
