### ISSUE TITLE
Skybox.backgroundTexture is ignored when blurBackground is true

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#266]

**Comment by dmnsgn** [comment]
Issue: if backgroundBlur > 0, texture 

https://github.com/pex-gl/pex-renderer/blob/5cced079d6b6330cf42656c57200d2c49e517806/skybox.js#L112-L128

TODO v4: add back backgroundTexture support (added here https://github.com/pex-gl/pex-renderer/commit/77cffc9bddaab73e2fc56014dccce5e146bdbbed) and handle above issue here:

https://github.com/pex-gl/pex-renderer/blob/90a39cb5b751e67eb8390aacff0ccb2bbcaa81c8/systems/renderer/skybox.js#L92-L100

**Comment by vorg** [comment]
Removed in favour of `uBackgroundBlur`
