### ISSUE TITLE
[glTF] URI-decode all URIs present in a glTF model

### ISSUE THREAD

**Issue by dmnsgn** [pex-gl/pex-renderer#292]
A new sample model has been added to test URI: https://github.com/KhronosGroup/glTF-Sample-Models/tree/master/2.0/Box%20With%20Spaces

Our implementation will fail:
https://github.com/pex-gl/pex-renderer/blob/18746d1869dc11c9ca2bcff1eaaad428cd9b98e7/loaders/glTF.js#L937

Fix:
```js
url: decodeURIComponent([basePath, image.uri].join('/')),
```

**Comment by vorg** [comment]
I did have issues with spaces, so thats good catch

**Comment by dmnsgn** [comment]
Fixed in v4 b37f93d29c0f764b166ed70cde8a623deabdc133
