### ISSUE TITLE
Custom shader shadows are missing

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#303]
![Screenshot 2022-06-06 at 15 50 28](https://user-images.githubusercontent.com/171001/172185550-8f42be41-e77d-4527-afc8-de0a151a6bfe.jpg)

we have them in thumbnail though

![custom-shader](https://user-images.githubusercontent.com/171001/172185569-3bd20aa2-e45a-423f-9d45-a5b10a6526ee.png)

**Comment by dmnsgn** [comment]
TODO v4: either port this example based on basic-engine and hooks or remove.
