### ISSUE TITLE
Consider renaming maps to textures

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#310]
So `baseColorMap` to `baseColorTexture` and `normalMap` to `normalTexture` etc...

pex-renderer -> map
ThreeJS -> map
Unity -> map
Unreal -> map

ecs in Nodes -> texture
Babylon -> texture
cables.gl -> texture
godot -> texture
gltf -> texture

**Comment by dmnsgn** [comment]
It's a question of type = what it is (texture object) vs function = what it does (mapping to poly).

In 3D software world:
- blender: map
- C4D: map
- 3DSmax: map

**Comment by vorg** [comment]
Also looking at modern engines
bevy: texture
machinery: texture
tool3: map
xenko/stride: map

So that's the thing. Data / port / prop is type texture. Shader can call it map or not. But that is always confusing in uniforms setup where i need `uBaseColorMap: material.baseColorTexture` (or was it Tex? or was it Map?)

I would say props should follow gltf as much as possible. Normalizing everyting to texture would simplify things.

**Comment by vorg** [comment]
WGSL having `texture_2d` uniform type is the winning vote for `*Texture` names.
