### ISSUE TITLE
Component namespacing

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#314]
I miss destructuring a bit

```javascript
const { components: { lights: { directional: directionalLight } } } = 
require("pex-renderer")
``` 

Any preference? 

1. (current)
```javascript
import {
  components,  
} from "pex-renderer";

const e = {
  directionalLight: components.directionalLight()
}
```

2.
```javascript
import {
  components,  
} from "pex-renderer";

const lights = components.lights

const e = {
  directionalLight: components.light.directional()
}
```

3.
```javascript
import {
  directional as directionalLight,  
} from "pex-renderer/components/lights/directional.js";

const lights = components.lights

const e = {
  directionalLight: directionalLight()
}
```

**Comment by dmnsgn** [comment]
I would avoid 3. (deep import in packages currently cause me more headache and might confuse bundlers), keep pex-renderer exporting components and rely on tree-shaking.

Not sure it is necessary to sub-namespace components so I'd stick with 1.

**Comment by vorg** [comment]
@simonharrisco mentions option 4.

```javascript
import { directionalLight } from "pex-renderer"

const e = {
  directionalLight: directionalLight()
}
```

**Comment by dmnsgn** [comment]
4. could simplify export in index.js:
```js
export { default as directionalLight } from "./components/directional-light.js";
// or
export * from "./components/index.js";
```
and also means only systems are namespaced?

**Comment by vorg** [comment]
> and also means only systems are namespaced?

No, if we move components up then systems too.

**Comment by dmnsgn** [comment]
> > and also means only systems are namespaced?
> 
> No, if we move components up then systems too.

We'd run into conflict for animation (both component and system) unless systems are suffixed (animationSystem).

**Comment by vorg** [comment]
Well that was the idea for name-spacing in the first place which looks like brings us back to current option 1.

**Comment by vorg** [comment]
We decided to leave flat list of components. Maybe later if list gets too big.
