### ISSUE TITLE
On scaling gltf scenes

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#317]
Because some gltf scenes are in milimeters and therefore super big our loaders have an option to normalize assets size to 1x1x1. It's is problematic with ECS as scene bounds are not known until first transformSystem pass. Therefore various versions of the code below are present in ECS based projects:

```js
renderEngine.transformSystem.update(world.entities);
rescaleScene(sceneEntities[0]);
```

Which is not pretty. Alternative solution:
- don't scale scenes -> fix your asset! current attitude after posting this issue
- expose transformSystem and update manually like above (will cause issues in Nodes)
- add some `normalizeOnFirstFrame` flag -> seems messy

Unless better solution is found i'll stick with the first option for now but wanted to document that the issue exists.

**Comment by dmnsgn** [comment]
> don't scale scenes -> fix your asset! current attitude after posting this issue

Unfortunately gltf sample models are all over the place in term of scaling.

Sounds like a good use case to have a "center and normalize scene system".

**Comment by vorg** [comment]
Could be quite good example on how to make your own system.

```js
if (enitity.normaliseScale && !aabb.ampty(entity.transform.worldBounds) {
  rescaleEntity(enitity)
  delete enitity.normaliseScale
}
```

**Comment by vorg** [comment]
Just instantiate temp transformSystem, update your scene graph worldBounds in loader (always) so the user can center and normalizeScale as it wishes.
