### ISSUE TITLE
Add support for attribute.dirty

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#334]
We need a way to update only one attribute e.g. offsets without re-uploading all others. One solution would be to add .dirty = true/false property. This could be also used for invalidating bouds and and manually asking for recalculating bounding box.

**Comment by dmnsgn** [comment]
Revived instancing example and use it to demo attribute.dirty: https://github.com/pex-gl/pex-renderer/commit/13ed4154a4c7bf97fb00f7161f466415ae643022#diff-b9928ed31347ca26a5db354cc663e6275c0a7266edafd38ca237539ca95d2cd0R184-R188


The main change in the system are:

- checking cached object difference upfront and updating properties:

https://github.com/pex-gl/pex-renderer/blob/13ed4154a4c7bf97fb00f7161f466415ae643022/systems/geometry.js#L53-L65

- checking for both upfront whole geometryDirty and attribute.dirty to skip update:

https://github.com/pex-gl/pex-renderer/blob/13ed4154a4c7bf97fb00f7161f466415ae643022/systems/geometry.js#L92

**Comment by dmnsgn** [comment]
Performance in example (updating offsets/rotations/colors only instead of positions/normals/uvs/cells/offsets/scales/rotations/colors): 10ms -> 3.5ms
