### ISSUE TITLE
Renderer crashes on directional lights that don't cast shadows

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#345]
Can't set uniform "uDirectionalLights[1].projectionMatrix" with a null value  as the _projectionMatrix is never defined (only for lights with castShadows) and yet it's required by renderer's uniform setting code

**Comment by dmnsgn** [comment]
Everything is set by:
- the light system: https://github.com/pex-gl/pex-renderer/blob/2a426d4d14b0d0b212d29f3d28b40f62c45ad1d9/systems/light.js#L9-L10

- the render pipeline: https://github.com/pex-gl/pex-renderer/blob/2a426d4d14b0d0b212d29f3d28b40f62c45ad1d9/systems/render-pipeline.js#L115-L116
https://github.com/pex-gl/pex-renderer/blob/2a426d4d14b0d0b212d29f3d28b40f62c45ad1d9/systems/render-pipeline.js#L170-L171

- the components defaults: https://github.com/pex-gl/pex-renderer/blob/9a8473b6ca2667fe71d3211cd00f6813da233016/components/directional-light.js#L9-L12
