### ISSUE TITLE
Add id to all created objects for debugging

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#37]

**Comment by dmnsgn** [comment]
Possible solutions :
1. generate UUID with hash code (potentially slower)
2. add a `let id = 0` per file and increment it as `this.id = id++` (fast and relies on hoisting in a file)

any other idea @vorg ?

I would go for 2. as it seems easier to reason about than randomly generated strings.

**Comment by vorg** [comment]
In pex context we append id to every new created resource

https://github.com/pex-gl/pex-context/blob/master/index.js#L377

```javascript

let ID = 0

resource: function (res) {
   res.id = res.class + '_' + ID++
}

textureCube: function (opts) {  
  return this.resource(createTexture(this, opts))
},
```

We could do the same in renderer or have local id counters per class

**Comment by dmnsgn** [comment]
Would it make sense to have a component.js file for each individual components to extend/compose from? 

Something in these lines:
```js
let ID = 0
function Component(opts) {
  this.id = ID++
  this.type = 'Component'
  this.entity = null
  this.changed = new Signal()

  this.set(opts)
}

Component.prototype.init = function (entity) {
  this.entity = entity
}

Component.prototype.set = function (opts) {
  Object.assign(this, opts)
  Object.keys(opts).forEach((prop) => this.changed.dispatch(prop))
}

Component.prototype.dispose = function () {
  this.changed.dispose()
}
```

**Comment by vorg** [comment]
In principle i'm ok with Component base class.

- Which method of inheritance would we use here e.g. `Camera.prototype = Object.create(Component)`?
- how do we call parent class e.g. `set()` in [Camera](https://github.com/pex-gl/pex-renderer/blob/master/camera.js#L102)

**Comment by dmnsgn** [comment]
Solution 1 would be to go more OOP style and use `class` `extends` and call `super.set()`:
```js
class CustomComponent extends Component {
  constructor(opts) {
    super(opts)
  }

  set(opts) {
    super.set(opts)
    // Custom setting
  }
}
```

Solution 2 is the function/prototype equivalent:
```js
function CustomComponent(opts) {
  Component.call(this, opts);
}

CustomComponent.prototype.set = (opts) => {
  Component.prototype.set.call(this, opts)
  // Custom setting
}

CustomComponent.prototype = Object.create(Component.prototype);
CustomComponent.prototype.constructor = CustomComponent;
```

**Comment by vorg** [comment]
So to create custom component we need to add more exports to main `pex-renderer` module so we can do:

```javascript
const { createRenderer, Component } = require('pex-renderer')

// or
const Component = require('pex-renderer').Component

// or
const Component = require('pex-renderer/Component')
```

**Comment by vorg** [comment]
The problem with Components class is that we do "opts enhancement " in factory functions

```javascript
Renderer.prototype.skybox = function (opts) {
  return createSkybox(Object.assign({ ctx: this._ctx, rgbm: State.rgbm }, opts))
}
```

we could consider passing ctx and state vars via init [in the entity](https://github.com/pex-gl/pex-renderer/blob/master/entity.js#L27)

```javascript
//renderer.entity([ renderer.transform(), renderer.geometry() ])
this.components.forEach((component) => component.init(this))
```

**Comment by vorg** [comment]
Doesn't seem to be relevant anymore. Closing for now.
