### ISSUE TITLE
Reduce online dependencies in examples

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#370]
Google Fonts, @thi.ng/dot, @hpcc-js/wasm/graphviz as it makes some examples not runnable on slow/no internet

**Comment by vorg** [comment]
Could we have them as dev-dependencies? @dmnsgn

**Comment by dmnsgn** [comment]
Looks like graphviz now works properly.
Pushed on v4 branch.

Google Fonts have display swap so that shouldn't have an impact.
