### ISSUE TITLE
Double pass transmission

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#375]
Similar to here https://github.com/mrdoob/three.js/pull/25502

![Screenshot 2024-05-13 at 13 15 32](https://github.com/pex-gl/pex-renderer/assets/171001/75c5c5bf-50fd-4413-ba0a-b49e9878dfdb)

**Comment by dmnsgn** [comment]
On when cullFace = false.
Closed by 704a309958b0fa341f0f6086857ed300466a1ca9
