### ISSUE TITLE
Transmission IBL reflection color is wrong

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#379]
Reflection color should be tinted by attenuationColor but for any value outside of 1 and 0 it becomes instantly white e.g. 1,0.1,0.1 seem not to colorize reflections at all while 1,0,0 does.

Compare with three.js example where reflections are yellow on yellow dragon
https://threejs.org/examples/webgl_materials_physical_transmission_alpha.html

![Image](https://github.com/pex-gl/pex-renderer/assets/171001/437ad5a3-4f68-4590-af16-2f8140d959e2)

**Comment by dmnsgn** [comment]
Isn't that just the envmap? Using the same hdr in Dragon Atteniation model in our gltf example: 

<img width="1088" alt="image" src="https://github.com/pex-gl/pex-renderer/assets/1636460/dd7538e0-cee6-4f99-891a-b9c9c9643b8d">

**Comment by vorg** [comment]
I think you are right and the envmap was in warm tones.

From [Arnold](https://help.autodesk.com/view/ARNOL/ENU/?guid=arnold_user_guide_ac_legacy_standard_ac_legacy_specular_html)
> The color the specular reflection will be modulated with. Use this color to 'tint' the specular highlight. You should only use colored specular for certain metals, whereas non-metallic surfaces usually have a monochromatic specular color. **Non-metallic surfaces normally do not have a colored specular.**
