### ISSUE TITLE
Fallback for max num supported textures

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#39]
Adding more lights with shadows maps can bump number of textures higher than max supported (e.g. 16). Additional lights should have shadows disabled or a warning issued.

**Comment by dmnsgn** [comment]
Dependent on https://github.com/pex-gl/pex-context/pull/61/

**Comment by dmnsgn** [comment]
Shouldn't this be handled in pex-context directly?

**Comment by vorg** [comment]
I can't think of easy solution for that on engine level. PBR Material itself has 6 maps, + 2 for area light + lightprobe + ambient occlusion = 10. That leaves us 6 slots for lights (on MBP we have limit of 16). An only assuming we don't have customized shader.

Where would failure need to occur? We can add 7 lights and everything is ok until we add normal mapping or enable SSAO. With maxTextureImageUnits in `pex-context` implemented I would say this is user space check.
