### ISSUE TITLE
Installing module with invalid name crashes server

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#43]
![Screen Shot 2018-02-26 at 14.33.35.png](https://shipusercontent.com/64b6c1fb46c96d82208a9fa0d8a8e56c/Screen%20Shot%202018-02-26%20at%2014.33.35.png)

![Screen Shot 2018-02-26 at 14.33.04.png](https://shipusercontent.com/a3d8f4bb761cb61697326766ba552cdc/Screen%20Shot%202018-02-26%20at%2014.33.04.png)

**Comment by nicknikolov** [comment]
Wrong repo
