### ISSUE TITLE
Verify and document equirect panorama orientation

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#47]
It's different than other engines https://github.com/vorg/pbr-compare

![screenshot](https://user-images.githubusercontent.com/171001/39817488-33840b28-5396-11e8-9526-ce9c36a9a6e1.jpg)

I think it's different as i made it so it matches RTT FBOs,

**Comment by vorg** [comment]
Lol everybody is different..

PEX
https://github.com/pex-gl/pex-renderer/blob/master/shaders/chunks/env-map-equirect.glsl.js
```glsl
vec2 envMapEquirect(vec3 wcNormal) {
  float flipEnvMap = -1.0;
  // I assume envMap texture has been flipped the WebGL way (pixel 0,0 is a the bottom)
  // therefore we flip wcNorma.y as acos(1) = 0
  float phi = acos(-wcNormal.y);
  float theta = atan(wcNormal.x, flipEnvMap * wcNormal.z) + PI;
  return vec2(theta / TWO_PI, phi / PI);
}
```

ThreeJS
https://github.com/mrdoob/three.js/blob/dev/src/renderers/shaders/ShaderLib/equirect_frag.glsl.js
```glsl
vec3 direction = normalize( vWorldDirection );
	vec2 sampleUV;
	sampleUV.y = asin( clamp( direction.y, - 1.0, 1.0 ) ) * RECIPROCAL_PI + 0.5;
	sampleUV.x = atan( direction.z, direction.x ) * RECIPROCAL_PI2 + 0.5;
	vec4 texColor = texture2D( tEquirect, sampleUV );
```

BabylonJS
https://github.com/BabylonJS/Babylon.js/blob/master/src/Shaders/ShadersInclude/reflectionFunction.fx#L21
```glsl
        vec3 direction = normalize(vDirectionW);
	float lon = atan(direction.z, direction.x);
	float lat = acos(direction.y);
	vec2 sphereCoords = vec2(lon, lat) * RECIPROCAL_PI2 * 2.0;
	float s = sphereCoords.x * 0.5 + 0.5;
	float t = sphereCoords.y;	
        #ifdef REFLECTIONMAP_MIRROREDEQUIRECTANGULAR_FIXED
		return vec3(1.0 - s, t, 0);
	#else
		return vec3(s, t, 0);
	#endif
```

ClayGL
https://github.com/pissang/claygl/blob/master/src/shader/source/skybox.glsl#L43
```glsl
   vec3 eyePos = viewInverse[3].xyz;
    vec3 V = normalize(v_WorldPosition - eyePos);
#ifdef EQUIRECTANGULAR
    float phi = acos(V.y);
    // consistent with cubemap.
    // atan(y, x) is same with atan2 ?
    float theta = atan(-V.x, V.z) + PI * 0.5;
    vec2 uv = vec2(theta / 2.0 / PI, phi / PI);
    vec4 texel = decodeHDR(texture2D(environmentMap, fract(uv)));
#else
```

@dmnsgn can you push filament upstream?

**Comment by vorg** [comment]
Looking at my own blog post http://marcinignac.com/blog/pragmatic-pbr-hdr/
![301_pisa_streetview](https://user-images.githubusercontent.com/171001/54798093-4e122f80-4c9a-11e9-99e6-69b3be640f8b.jpg)

It would look like North is to the right so ThreeJS/Babylon are correct.

**Comment by vorg** [comment]
![Screenshot 2018-09-27 at 12 47 16](https://user-images.githubusercontent.com/171001/54799183-7fd9c500-4c9f-11e9-8b36-c98188337efb.jpg)

I've made example to test all this before but need to find the source code for it.

**Comment by vorg** [comment]
Uhm, consensus is a bit complicated if the source files are different..

assets/Pisa/three/nz.png
![nz](https://user-images.githubusercontent.com/171001/54803252-16af7d00-4cb2-11e9-80f9-ef4633ee2837.png)

assets/Pisa/pex/pisa/negz.hdr
<img width="251" alt="Screenshot 2019-03-22 at 14 53 48" src="https://user-images.githubusercontent.com/171001/54803303-50808380-4cb2-11e9-9198-8c732b60ce59.png">

Actual code in pex and babylon use equirect panorama (here with added face overlay, red=X)

![Screenshot 2019-03-22 at 14 55 59](https://user-images.githubusercontent.com/171001/54803385-a6edc200-4cb2-11e9-97e3-1d19379bfd15.jpg)

**Comment by vorg** [comment]
So I checked What Would YouTube Say with their equirect video spec.


There is 360 video PR mentioning "fixed" "mirrored" equirectangular texture. Digging what does it mean.
material.reflectionTexture.coordinatesMode = BABYLON.Texture.FIXED_EQUIRECTANGULAR_MIRRORED_MODE; // matches src

**Comment by vorg** [comment]
@dmnsgn would you know how to load equirect hdr as bg in three?

**Comment by dmnsgn** [comment]
> @dmnsgn can you push filament upstream?

Just did but atm:
- no support for Chrome 73 (will be fixed next version) so only in Firefox (which is struggling but you can see it on its own here: https://dmnsgn.github.io/pbr-compare/build/filament.html)
- their assets for env map have a specific format, I have to find a tool to convert pisa

> Uhm, consensus is a bit complicated if the source files are different..

I have removed all ldr format and only using .hdr (except for playcanvas because it's impossible to find an example using .hdr). https://github.com/dmnsgn/pbr-compare/tree/master/assets/Pisa
Then hopefully the splitted hdr `['px.hdr', 'nx.hdr', 'py.hdr', 'ny.hdr', 'pz.hdr', 'nz.hdr'],` have the correct orientation 🤔?

> @dmnsgn would you know how to load equirect hdr as bg in three?
Loading a single hdr file is not possible yet: https://github.com/mrdoob/three.js/issues/9688

**Comment by vorg** [comment]
Official filament don't run in FF on my machine somehow, yours aldo doesn't. I get ctx is null 🤔 

For cubemaps there is tool `cmgen` (cubemap gen). Example here https://github.com/google/filament/blob/a38c40cf1136c5f3c7e310dba0d53e7d567e5343/web/docs/tutorial_suzanne.md#bake-environment-map

**Comment by vorg** [comment]
Arnold VR Camera https://docs.arnoldrenderer.com/display/A5AFCUG/VR+Camera
![LatLong](https://user-images.githubusercontent.com/171001/54820887-f3052a80-4ce3-11e9-9d17-0d899fac2d9d.png)

Paul Bourke http://paulbourke.net/miscellaneous/cubemaps/
![test2](https://user-images.githubusercontent.com/171001/54820967-2e075e00-4ce4-11e9-91a1-5f6559f6c201.gif)

Panorama in question
![pisa_env](https://user-images.githubusercontent.com/171001/54820977-39f32000-4ce4-11e9-9b24-aa3d92db9022.jpg)

No matter if front is +Z or -Z that axis is along the street (like pex) not along the wall (like three and babylon)
