### ISSUE TITLE
Enable required extensions

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#53]
Currently all projects need to add extension queries before creating Renderer instance. This should be done internally.

```javascript
ctx.gl.getExtension('EXT_shader_texture_lod')
ctx.gl.getExtension('OES_standard_derivatives')
ctx.gl.getExtension('WEBGL_draw_buffers')
ctx.gl.getExtension('OES_texture_float')
```

**Comment by vorg** [comment]
> Would there be a reason to change that in pex-context?

I would not, they are all just different types of capabilities.

**Comment by dmnsgn** [comment]
@vorg The other question here is: is there a cost associated to calling getExtension because we don't always need all of the one listed in pex-context?


https://developer.mozilla.org/en-US/docs/Web/API/WebGLRenderingContext/getExtension
> The WebGLRenderingContext.getExtension() method enables a WebGL extension.
