### ISSUE TITLE
Implement Orbiter

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#57]
Requiring `pex-cam` just to create fake camera and orbiter on top of it and then manually translate that to `pex-renderer` transform rotation is too cumbersome. A better for now (until pex-cam is generalized?) would be to copy orbiter code and make it work without pex-cam/perspective camera class.

**Comment by vorg** [comment]
Proposed API

```javascript
const camera = renderer.entity([
  renderer.camera({
    fov: Math.PI / 2,
    aspect: ctx.gl.drawingBufferWidth / ctx.gl.drawingBufferHeight,
    near: 0.1,
    far: 100,
    postprocess: true,
    fxaa: true
  }),
  renderer.orbiter({
    target: [0, 0, 0],
    position: [0, 0, 2]
  })
])
```

**Comment by vorg** [comment]
One issue i have is pex-cam/orbiter implementation is using camera viewMatrix both for reading and writing and then updates transform component. On next update camera component will then overwrite it's own viewMatrix from inverted worldTransformMatrix from the transform component..

**Comment by simonharrisco** [comment]
I just came across this independently and was about to query about it.

From my perspective it seemed odd that in the example it used:

`const camera = renderer.entity([
  renderer.transform({ position: [0, 0, 3] }),
  renderer.camera({
    fov: Math.PI / 2,
    aspect: ctx.gl.drawingBufferWidth / ctx.gl.drawingBufferHeight,
    near: 0.1,
    far: 100
  })
])`

but this doesn't work with 

`createOrbiter(`

I was wondering where my configuration went wrong. Im not an expert at code structure but the surely the orbiting controls are a camera feature not an rendering one so

`
const camera = renderer.entity([
  renderer.camera({
    fov: Math.PI / 2,
    aspect: ctx.gl.drawingBufferWidth / ctx.gl.drawingBufferHeight,
    near: 0.1,
    far: 100,
    postprocess: true,
    fxaa: true,
    controls : orbiter({
       position: [0,0,0], 
       target: [0,0,1]
     })
  }),
])
`
This makes more sense to me but Im less familiar with the overall codebase

**Comment by vorg** [comment]
createOrbiter is `pex-cam` method that creates orbiter class that works with perspective camera also from `pex-cam`

`renderer.orbiter()` is pex-renderer component that modifies transform of the node, not the camera

**Comment by vorg** [comment]
Yes, it's confusing but `pex-cam/perspective` does two things in one (camera optics like fov, camera orientation like target) while pex-renderer camera is just optics

**Comment by vorg** [comment]
It has been implemented now
