### ISSUE TITLE
Formalise use of linter and formatter

### ISSUE THREAD

**Issue by dmnsgn** [pex-gl/pex-renderer#65]

**Comment by dmnsgn** [comment]
Reached consensus:
- formatter: prettier with no semi and single-quote
- linter: eslint with eslint-plugin-prettier and eslint-config-prettier

**Comment by vorg** [comment]
Are those VSCode plugins or I to install something different? Would love to test it before we start pishing commits changing every single line.

**Comment by dmnsgn** [comment]
Nope, just npm install this branch https://github.com/pex-gl/pex-renderer/tree/65-formater-linter and add your editor integration: https://prettier.io/docs/en/editors.html and format (I formatted the README in the branch for a first example as it also formats code blocks in markdown files)

**Comment by dmnsgn** [comment]
package.json updated to match pex-context. Waiting for all PR to be merged before formatting the codebase.

Details for the config:

https://github.com/pex-gl/pex-context/pull/65#issuecomment-472936053
