### ISSUE TITLE
Add convenience method to Transform component

### ISSUE THREAD

**Issue by simonharrisco** [pex-gl/pex-renderer#68]
Continuing a conversation:

Geometry/Transform helper functionality seems backwards, for example;
 -  stuff like finding the distance between 2 points can be handled by pex-maths
- Hard stuff like, rotate geometry around a point - you’re out of luck I hope you’re good at matrices and quaternions. Made more difficult by an (understandable) lack of euler angle support. 
- Perhaps is linked to the lack of a generic object class in a scene graph that can be used for movement of manipulation, unless i have missed some of the functionality of entities.

- Unity has GameObject
- Unreal has Actors
- Three has Object3D

This all have properties and methods that can be run

**Comment by simonharrisco** [comment]
I suppose Im suggesting an extension to the transform component:
https://docs.unity3d.com/ScriptReference/Transform.html
This is unity’s see methods such as rotateAround and lookAt and properties such as up.

**Comment by simonharrisco** [comment]
marcins response: 

```
Entity.transform.rotation = quat.fromEuler(quat.create(), [Math.PI/2, 0, 0])
//that requires beta pex-math@3.0.0-0
quat.setAxisAngle(q, axis, angle)
Etc
```

One missing thing is quat.lookAt. Right now we have only quat.fromTo(q, fromDir, toDir) so you need to do something like quat.fromTo(quat.create(), [0, 0, 1], vec3.normalize([-1, -1, -1]))...
quat.lookAt would take 2 points and compute dir itself so you could do quat.lookAt(quat.create() [0, 2, 5], [0, 0, 0]) the only issue i have with that name is same as mat4.lookAt which includes both rotation AND translation

**Comment by vorg** [comment]
Another comment might be that some of the issues come from minimising API surface (vs pex < 2.0 our math was 3x bigger), automagic (defaults and guessing) and multiple ways of doing things (like regl where you can create buffer in multiple ways to the point where you can't reason about performance impact).

**Comment by vorg** [comment]
[pex-math: Implement quat.lookAt](https://github.com/pex-gl/pex-math/issues/14)

**Comment by simonharrisco** [comment]
What you suggested above is using maths functions **and a knowledge of relatively complex geometry** to modify values.

I suggesting that by adding these as methods of the transform component is makes life simpler and is more friendly for newer people.
New people might not even know what quaternions are, or even the mentality shift that what you're doing when you rotate a cube in 3d space is a geometric transformation.

**Comment by simonharrisco** [comment]
there is a mentality shift between x.transform.rotation.set(maths) and x.transform.rotate([0,0,1])

**Comment by vorg** [comment]
Next step:
- implement [quat.targetTo](https://github.com/pex-gl/pex-math/issues/14)

**Comment by dmnsgn** [comment]
v4: transform component are now plain data. pex-math v3 has the new methods https://github.com/pex-gl/pex-math/pull/27
