### ISSUE TITLE
Implement Helpers

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#72]
Currently debug mode (used to draw bounding boxes) it not working as it depends on outdated pex-draw. Either fix it or remove it.

**Comment by vorg** [comment]
@dmnsgn Would you mind commenting on how do you see support for this? I.e. what do we need? Wireframe gizmo per model showing light direction / zone of influence and eg. bounding boxes for geometry enabled per entity or per component?

**Comment by dmnsgn** [comment]
First of all, I prefer the name `helpers` to `gizmos` (look up gizmo definition, and you'll see why).

I'd say we need the following helpers:
- Light helpers (those currently in the lights example): they check which type of light is in the entity
- EntityBoundingBox helper: not sure about GeometryBoundingBox as the BB is stored in an entity transform
- Frustum or Camera helper
- Normals helper

Nice to have:
- TransformHelper: move around by dragging anchors (like in any good 3d software)
- AnimationHelper: show animation weights ?

As for the API, we could have components with a generic `type = 'Helper'` and check that for `drawMeshes`:
```js
// Light
renderer.entity([
  renderer.lightHelper({
    enabled: true,
    color: [1, 0, 1, 1]
  }),
  renderer.directionalLight(),
])

// Camera
renderer.entity([
  renderer.frustumHelper({
    enabled: true
  }),
  renderer.camera()
])

// Geometry
renderer.entity([
  renderer.boundingBox({
    enabled: true,
    color: [1, 1, 0, 1]
  }),
  renderer.normalsHelper({
    enabled: true,
    faces: true,
    vertices: false,
    length: 2
  }),
  renderer.geometry(createSphere(1)),
  renderer.material()
])
```

**Comment by vorg** [comment]
Thinking what's the right API here.

General considerations
- What's the primary use case? Most often I would enable frustum for a camera, light helpers so i can see where they are and what they point at and maybe few bounding boxes for key or selected geometry. 
- That means global debug mode (enable helpers for all objects) is not necessary
- Implementation: one big mesh builder updated every frame from scratch (leans towards option 3 below) vs multiple smaller object tracking their components (leans towards option 1 below). Most helpers would be ok with redrawing every frame while others like NormalsHelper will be super expensive...

### 1. Helper component:
```javascript
renderer.entity([
  renderer.lightHelper({
    enabled: true,
    color: [1, 0, 1, 1]
  }),
  renderer.directionalLight(),
])
```
Pros:
- it's clear what does it do
- enables distinct helpers for distinct functions (e.g. both bounding box and transform RTS controls separately)
Cons: 
- more objects to create
- what happens if we have helper for component that doesn't exist


### 2. Helper property
```javascript
renderer.entity([
  renderer.directionalLight({
     helper: true
  }),
])
```
Pros: smaller api
Cons: confusing for components with many possible helpers

### 3. ShowX property
Pros: explicit
Cons: verbose?
```javascript
renderer.transform({
   showTransformHelper: true,
   showBoundingBoxHelper: true
 }),
renderer.entity([
  renderer.directionalLight({
     showHelper: true
  }),
  renderer.geometry({
     showNormalsHelper: true
  })
])
```

**Comment by vorg** [comment]
When implementing here is supporting source code
- Gizmos PR https://github.com/pex-gl/pex-renderer/pull/31
- examples helpers.js https://github.com/pex-gl/pex-renderer/blob/master/examples/helpers.js
- pex-helpers https://github.com/pex-gl/pex-helpers/tree/master/lib

**Comment by dmnsgn** [comment]
I'd go for option 1 as it fits best the pseudo ECS paradigm. 

> - more objects to create

Helpers are only here for dev so performance impact should be separated. Agree it might become tedious to create object instead of adding a `helperProperty: true` but with good autocomplete and template Nodes the pain could be eased.

- what happens if we have helper for component that doesn't exist

> console.warn ?

**Comment by vorg** [comment]
> I'd go for option 1 as it fits best the pseudo ECS paradigm.

True.

Just for the note. Approach 3 would play nice with material debugging


```javascript
  renderer.geometry({
     showNormalsHelper: true
  }),
  renderer.material({
    showAO: true
  })
])

**Comment by vorg** [comment]
### 4. renderer.helper

```javascript
renderer.entity([
  renderer.helper({
     showTransform: true,
     showWorldBoundingBox: true,
     showNormals: true
  }),  
  // or
  renderer.debug({
     transform: { enabled: true, color: [1, 0, 0, 1] },
     worldBoundingBox: { enabled: true, color: [1, 0, 1, 1] },
     normals: { enabled: true, color: [1, 1, 0, 1] },
  }),  
])
```

**Comment by vorg** [comment]
Top priority
- cameraHelper (frustum)
- lightHelper (position, orientation, range)
- boundingBoxHelper (default to world, not local, skinning support anyone?)
- axesHelper (axes, not axis? local transform coordinate system basis)

Maybe later
- normalsHelper (vertex, not face)
- transform -> transformGizmo (translation, rotation, scale)

**Comment by vorg** [comment]
Todo
- [ ] add geom builder
- [ ] add show colors shader for drawing lines
- [ ] add line drawing pipeline
- [ ] create helpers example with
  - [ ] 2 cameras
  - [ ] 4 lights
  - [ ] static mesh
  - [ ] animated mesh
  - [ ] skinned me
  - [ ] instanced mesh
- [ ] create boundingBoxHelper and add to the example
- [ ] on each scene draw collect all helpers and update geometryBuilder
- [ ] draw helpers mesh (see through ? or with depth test?)
- [ ] create lights helper
- [ ] create cameraHelper
- [ ] create axesHelper

**Comment by vorg** [comment]
Started new branch here https://github.com/pex-gl/pex-renderer/commits/72-helpers

**Comment by vorg** [comment]
as for file names i would follow loaders convention and use

```
pex-renderer/helpers/bounding-box.js
pex-renderer/helpers/camera.js
...
```

**Comment by vorg** [comment]
Unless we all happy to use but it's confusing

```
pex-renderer/helper-bounding-box.js //BoundingBoxHelper  -> renderer.boundingBoxHelper
pex-renderer/helper-camera.js //CameraHelper  -> cameraHelper
```

**Comment by dmnsgn** [comment]
```
pex-renderer/helpers/bounding-box.js
pex-renderer/helpers/camera.js
```

sounds good unless we're up to move all components in a `component` folder:

```
pex-renderer/components/helpers/bounding-box.js
pex-renderer/components/helpers/camera.js
pex-renderer/components/camera.js
pex-renderer/components/area-light.js
...
```
