### ISSUE TITLE
Update packages in examples

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#73]
- [ ] blocks - debug, fresh, node-mime
- [ ] gltf - lodash
- [ ] overlays - debug
- [ ] gltf-morph - lodash

<img width="727" alt="screen shot 2018-08-12 at 23 47 44" src="https://user-images.githubusercontent.com/171001/44007276-39a09f78-9e8a-11e8-8769-23e54fdb5892.png">

<img width="729" alt="screen shot 2018-08-12 at 23 47 52" src="https://user-images.githubusercontent.com/171001/44007277-39b881ce-9e8a-11e8-942c-c75b967d1793.png">

<img width="732" alt="screen shot 2018-08-12 at 23 48 02" src="https://user-images.githubusercontent.com/171001/44007278-39d03de6-9e8a-11e8-9670-31bf280fe950.png">

<img width="728" alt="screen shot 2018-08-12 at 23 48 08" src="https://user-images.githubusercontent.com/171001/44007279-39e6fc0c-9e8a-11e8-8bf2-b0831db1684f.png">

**Comment by dmnsgn** [comment]
Fixed https://github.com/pex-gl/pex-renderer/commit/583d9545094607491d8a88b5fab176d427638b8f

More work on examples here: https://github.com/pex-gl/pex-renderer/issues/78
