### ISSUE TITLE
No shadows when cast shadow true: Bounding box calculation?

### ISSUE THREAD

**Issue by simonharrisco** [pex-gl/pex-renderer#82]
Strange behaviour when I turn off casting shadows, I thought this could be due to the bounding box not working correctly as it created this effect.

<img width="1905" alt="screen shot 2018-08-16 at 10 36 18" src="https://user-images.githubusercontent.com/36566034/44201325-dd71c600-a140-11e8-95f0-a41874f215d2.png">

I don't know the details of how bounding boxes work but if you receive a shadow this is should be within?

**Comment by nicknikolov** [comment]
Is it one geometry? Did you try logging the bounding box?

**Comment by vorg** [comment]
It's because we don't support bounding boxes for instanced geometry at the moment. Adding floor like on the image above should help though. Might be that the light orientation is wrong too.
