### ISSUE TITLE
Double check color space of glsl-atmosphere output

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#86]

**Comment by vorg** [comment]
https://github.com/pex-gl/pex-renderer/tree/master/local_modules/glsl-atmosphere

**Comment by dmnsgn** [comment]
It outputs linear. Clarified by moving tonemapping and encoding out of the chunk into the main shader: https://github.com/pex-gl/pex-shaders/blob/7b73ace45adec856e49e3122cee6651ec006a4cb/shaders/skybox/sky-env-map.frag.js#L41-L43
