### ISSUE TITLE
Using jpg as skybox texture is broken

### ISSUE THREAD

**Issue by vorg** [pex-gl/pex-renderer#87]
It looks like encoding is wrong

```javascript
loadImage(`assets/Mono_Lake_B.jpg`, (err, img) => {
  const panorama = ctx.texture2D({
    data: img,
    width: img.width,
    height: img.height,
    pixelFormat: ctx.PixelFormat.RGBA32,
    encoding: ctx.Encoding.sRGB,
    min: ctx.Filter.LinearMipmapLinear,
    mag: ctx.Filter.Linear,
    mipmap: true,
    flipY: true
  })
  skybox.getComponent('Skybox').set({ texture: panorama })
})
```

<img width="1086" alt="screen shot 2018-08-21 at 11 35 37" src="https://user-images.githubusercontent.com/171001/44396977-7dab5e80-a536-11e8-9aca-049609e202cd.png">

**Comment by dmnsgn** [comment]
Using the following [Mono_Lake_B asset](https://user-images.githubusercontent.com/1636460/55640269-2f945400-57c3-11e9-9936-117b47e432e7.jpg) and code :
```js
  const image = await io.loadImage(`${ASSETS_DIR}/Mono_Lake_B.jpg`)
  const panoramaImage = ctx.texture2D({
    data: image,
    width: image.width,
    height: image.height,
    pixelFormat: ctx.PixelFormat.RGBA8,
    encoding: ctx.Encoding.SRGB,
    flipY: true
  })

  const buffer = await io.loadBinary(`${ASSETS_DIR}/Mono_Lake_B.hdr`)
  const hdrImg = parseHdr(buffer)
  const panorama = ctx.texture2D({
    data: hdrImg.data,
    width: hdrImg.shape[0],
    height: hdrImg.shape[1],
    pixelFormat: ctx.PixelFormat.RGBA32F,
    encoding: ctx.Encoding.Linear,
    flipY: true
  })
```
results in gif below to compare:

![preview](https://user-images.githubusercontent.com/1636460/55639593-a7617f00-57c1-11e9-9e63-8765b25e70f3.gif)

It looks like the difference is now only in the loss of information from hdr to jpg. The uniform `uEnvMapEncoding` is used to decode jpg into linear here so we just need to remember to set `encoding: ctx.Encoding.SRGB,` on the jpg texture.
