### ISSUE TITLE
Docs say rotations twice when speaking about formats for instanced geometry attributes

### ISSUE THREAD

**Issue by simonharrisco** [pex-gl/pex-renderer#92]
^ https://github.com/pex-gl/pex-renderer#geometry--renderergeometryopts

**Comment by simonharrisco** [comment]
unless im mistaken it also says vec4 for scales and offsets and it should be vec3

**Comment by dmnsgn** [comment]
Fixing here: ea79d341eb720891cc53292ad865ad23b518dad8
