### ISSUE TITLE
Post processing optimisations

### ISSUE THREAD

**Issue by dmnsgn** [pex-gl/pex-renderer#99]
At the moment, all frame resources are allocated in `initPostproces` even if they are not activated.

The blit command requires some of these (bloom for instance) for the Postprocess program but could their instantiation be delayed (this.bloom onChange) and a placeholder used instead?

**Comment by vorg** [comment]
Yes, current architecture comes from times when i had SSAO only and now its inefficient.

In pex-fx (prec postprocessing lib) i had on demand resource allocation so you never allocate textures if not needed. With the right API this would enable texture reuse if not between effects then at least between cameras, seamless resolution changes and less code.

**Comment by dmnsgn** [comment]
The big triangle option might be worse exploring as well? https://michaldrobot.com/2014/04/01/gcn-execution-patterns-in-full-screen-passes/

**Comment by vorg** [comment]
I now defer allocating post-processing resources until needed https://github.com/pex-gl/pex-renderer/commit/d5c72c159e4877e0569a2aa10e41323ce36ee2e4

Issues:
- all textures and shaders are allocated even if we use only e.g. ssao
- there is not deallocation if post-processing is turned off later
